backend:
    name: github
    repo: dreonic/bk-website
    branch: decap-cms
    base_url: http://localhost:3000
    auth_endpoint: api/auth
    api_root: http://localhost:3000/api/github

media_folder: public/img
public_folder: /img

collections:
    - name: "faq"
      label: "FAQ"
      files:
          - label: "FAQ Content"
            name: "faq"
            file: "src/app/faq/content.md"
            fields:
                - label: "FAQ Items"
                  name: "faq"
                  widget: list
                  fields:
                      - {
                            label: "Question",
                            name: "question",
                            widget: "string",
                        }
                      - { label: "Answer", name: "answer", widget: "text" }

    - name: "events"
      label: "Events"
      files:
          - label: "Events Content"
            name: "events"
            file: "src/app/events/content.md"
            fields:
                - {
                      label: "Header Description",
                      name: "headerDescription",
                      widget: "text",
                  }
                - label: "Events by Year"
                  name: "events"
                  widget: list
                  fields:
                      - {
                            label: "Year",
                            name: "year",
                            widget: "number",
                            value_type: "int",
                        }
                      - label: "Year Events"
                        name: "yearEvents"
                        widget: list
                        fields:
                            - {
                                  label: "Event Image",
                                  name: "imageUrl",
                                  widget: "image",
                                  media_folder: "/public/events",
                                  public_folder: "/events",
                              }
                            - {
                                  label: "Event Type",
                                  name: "eventType",
                                  widget: "string",
                              }
                            - {
                                  label: "Event Name",
                                  name: "eventName",
                                  widget: "string",
                              }
                            - {
                                  label: "Description",
                                  name: "description",
                                  widget: "text",
                              }
